//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDatabaseAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int AccountNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PinNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string ProfileBase64 { get; set; }
    }
}
