//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DC_Practical_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Account_Number { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Pin_Number { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public byte[] Profile_Picture { get; set; }
    }
}
